// FilterForge shared type definitions
//
// Python-derived types are auto-generated by scripts/gen_bridge.py
// from src/python/filter_design.py. Re-exported here so all consumers
// import from '@/types/filter.ts' without knowing about the generated layer.

// Re-export Python-derived types (generated from TypedDict / Literal annotations)
export type {
  FilterType,
  Approximation,
  ComponentType,
  ComponentPosition,
  CircuitTopology,
  FilterParams,
  TransferFunction,
  FrequencyResponse,
  Component,
  FilterResult,
} from '@/generated/filter_design.types'

// Import types used locally in this file
import type { FilterParams, FilterResult } from '@/generated/filter_design.types'

// TS-only types (not derived from Python)

/** Frequency unit */
export type FrequencyUnit = 'Hz' | 'kHz' | 'MHz'

/** Filter design error code */
export type FilterDesignErrorCode =
  | 'PYODIDE_LOAD_ERROR'
  | 'INVALID_PARAMS'
  | 'CALCULATION_ERROR'

/** Filter design error */
export type FilterDesignError = {
  /** Error code */
  code: FilterDesignErrorCode
  /** User-facing error message */
  message: string
  /** Debug details */
  details?: string
}

/** Pyodide status */
export type PyodideStatus = 'idle' | 'loading' | 'ready' | 'error'

/** Worker API interface (exposed/wrapped via Comlink) */
export type FilterDesignWorker = {
  /** Initialize Pyodide + SciPy */
  initialize(onProgress?: (progress: number, message: string) => void): Promise<void>
  /** Design a filter */
  designFilter(params: FilterParams): Promise<FilterResult>
  /** Get current status */
  getStatus(): Promise<PyodideStatus>
}
